[build]
  command = "npm run build"
  publish = "dist"

# Redirecciones basadas en el host
[[redirects]]
  from = "/"
  to = "/data-analyst"
  status = 301
  force = true
  host = "da.armandochoa.com"

[[redirects]]
  from = "/"
  to = "/web-developer"
  status = 301
  force = true
  host = "wd.armandochoa.com"

# Manejar rutas SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
